blank_issues_enabled: false
contact_links:
  - name: 其他讨论
    url: https://github.com/eric2788/bilibili-vup-stream-enhancer/discussions
    about: 如你的问题并非基于bug或功能请求，你可以在讨论区提出
  - name: 联络作者
    url: https://t.me/eric1008818
    about: 如果你认为现有资源无法解答你的问题，你可以直接联系作者